moviesstore/accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('signup', views.signup, name='accounts.signup'),
    path('login/', views.login, name='accounts.login'),
    path('logout/', views.logout, name='accounts.logout'),
    path('orders/', views.orders, name='accounts.orders'),
    path('reset/', views.reset, name='accounts.reset'),
]

moviesstore/cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='cart.index'),
    path('<int:id>/add/', views.add, name='cart.add'),
    path('clear/', views.clear, name='cart.clear'),
    path('purchase/', views.purchase, name='cart.purchase'),
]

moviesstore/moviesstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesstore/passwordReset/urls.py
from django.urls import path
from . import views
from .views import NoEmailPasswordResetView

urlpatterns = [

]

moviesstore/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group

# Create your models here.

class CustomUser(AbstractUser):
    security_question = models.CharField(max_length=255)
    security_answer = models.CharField(max_length=255)
    custom_groups = models.ManyToManyField(
        Group,
        related_name="custom_users",
        blank=True,
    )

moviesstore/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from movies.models import Movie
from accounts.models import CustomUser

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ' - ' + self.user.username

class Item(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.IntegerField()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

moviesstore/passwordReset/models.py
from django.db import models

# Create your models here.

moviesstore/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe
from django import forms
from django.contrib.auth.forms import PasswordResetForm
from .models import CustomUser
from django.core.validators import MinLengthValidator
from django.core.validators import MaxLengthValidator

class CustomErrorList(ErrorList):
    def __str__(self):
        if not self:
            return ''
        return mark_safe(''.join([f'<div class="alert alert-danger" role = "alert">{e}<div>' for e in self]))

# Unused after hardcoding form in
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2', 'security_question', 'security_answer',)
        help_texts = {
            'username' : None,
        }

    CHOICES = [
        ('value1', 'What was your first pet\'s name?'),
        ('value2', 'What is the name of your elementary school?'),
        ('value3', 'What city did your parents meet each other?'),
    ]

    security_question = forms.ChoiceField(choices=CHOICES)
    security_answer = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['username'].widget.attrs.update({'minlength': '6', 'maxlength': '32', 'autocomplete': 'off'})
        self.fields['password1'].label = 'Password'
        self.fields['password1'].widget.attrs.update({'minlength': '8', 'maxlength': '32', 'autocomplete': 'off'})
        self.fields['password2'].label = 'Confirm Password'
        self.fields['password2'].widget.attrs.update({'minlength': '8', 'maxlength': '32', 'autocomplete': 'off'})
        self.fields['security_question'].label = 'Security Question'
        self.fields['security_answer'].label = 'Security Question Answer'
        self.fields['security_answer'].widget.attrs.update({'minlength': '4', 'maxlength': '32', 'autocomplete': 'off'})


        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {'class' : 'form-control'},
            )

        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

moviesstore/passwordReset/forms.py
from django import forms

moviesstore/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from .forms import CustomUserCreationForm, CustomErrorList
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import CustomUser

User = get_user_model()

CHOICES = [
        ('value1', 'What was your first pet\'s name?'),
        ('value2', 'What is the name of your elementary school?'),
        ('value3', 'What city did your parents meet each other?'),
]

@login_required
def logout(request):
    auth_logout(request)
    return redirect('home.index')

def login(request):
    template_data = {}
    template_data['title'] = 'Login'
    if request.method == 'GET':
        return render(request, 'accounts/login.html',
                       {'template_data': template_data})
    elif request.method == 'POST':
        user = authenticate(
            request,
            username = request.POST['username'],
            password = request.POST['password']
        )
    if user is None:
        template_data['error'] = 'Invalid username or password.'
        return render(request, 'accounts/login.html',
                      {'template_data': template_data})
    else:
        auth_login(request, user)
        return redirect('home.index')

def signup(request):
    template_data = {}
    template_data['title'] = 'Sign Up'

    if request.method == 'GET':
        template_data['choices'] = CHOICES
        return render(request, 'accounts/signup.html',{'template_data': template_data})
    elif request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        security_question = request.POST['security_question']
        security_answer = request.POST['security_answer']

        if not CustomUser.objects.filter(username=username).exists():
            if password1 == password2:
                user = CustomUser.objects.create_user(username=username, password=password1, security_question=security_question, security_answer=security_answer)
                auth_login(request, user)
                return redirect('home.index')
            else:
                template_data['error'] = 'Passwords do not match.'
                template_data['choices'] = CHOICES
                return render(request, 'accounts/signup.html',{'template_data': template_data})
        else:
            template_data['error'] = 'Username already taken.'
            template_data['choices'] = CHOICES
            return render(request, 'accounts/signup.html',{'template_data': template_data})

        # if form.is_valid():
        #     print(request.POST)
        #     user = form.save()
        #     auth_login(request, user)
        #     return redirect('home.index')
        # else:
        #     return render(request, 'accounts/signup.html',{'template_data': template_data})

def reset(request):
    template_data = {}
    template_data['title'] = 'Reset Password'

    if request.method == 'GET':
        template_data['choices'] = CHOICES
        return render(request, 'accounts/reset.html', {'template_data': template_data})

    elif request.method == 'POST':
        username = request.POST['username']
        new_password = request.POST['new_password']
        security_question = request.POST['security_question']
        security_answer = request.POST['security_answer']

        try:
            user = CustomUser.objects.get(username=username)

            if user.security_question == security_question:
                if user.security_answer == security_answer:
                    if not user.check_password(new_password):
                        user.set_password(new_password)
                        user.save()

                        template_data['error'] = 'Success!'

                        return redirect('home.index')
                    else:
                        template_data['error'] = "New password must not match previous password."
                else:
                    template_data['error'] = 'Invalid security question or answer.'
            else:
                    template_data['error'] = 'Invalid security question or answer.'
        except User.DoesNotExist:
            template_data['error'] = 'User does not exist.'
    template_data['choices'] = CHOICES
    return render(request, 'accounts/reset.html', {'template_data': template_data})

@login_required
def orders(request):
    template_data = {}
    template_data['title'] = 'Orders'
    template_data['orders'] = request.user.order_set.all()
    return render(request, 'accounts/orders.html',{'template_data': template_data})

moviesstore/passwordReset/views.py
from django.shortcuts import render

# Create your views here.

moviesstore/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="p-3 mt-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card shadow p-3 mb-4 rounded">
                        <div class="card-body">
                            Login
                            </h2>
                            <hr />
                            {% if template_data.error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ template_data.error }}
                                </div>
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                <p>
                                    <label for="username">Username</label>
                                    <input id="username" type="text" name="username" required autocomplete="username" class="form-control">
                                </p>
                                <p>
                                    <label for="password">Password</label>
                                    <input id="password" type="password" name="password" required autocomplete="current-password" class="form-control">
                                </p>
                                <div class="text-center">
                                    <button type="submit" class="btn bg-dark text-white">
                                        Login
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

moviesstore/accounts/templates/accounts/orders.html
{% extends 'base.html' %}
{% block content %}
    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col mx-auto mb-3">
                    <h2>My Orders</h2>
                    <hr />
                    {% for order in template_data.orders %}
                        <div class="card mb-4">
                            <div class="card-header">
                                Order #{{ order.id }}
                            </div>
                            <div class="card-body">
                                <b>Date:</b> {{ order.date }}<br />
                                <b>Total:</b> ${{ order.total }}<br />
                                <table class="table table-bordered table-striped text-center mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Item ID</th>
                                        <th scope="col">Movie</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">Quantity</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in order.item_set.all %}
                                        <tr>
                                            <td>{{ item.movie.id }}</td>
                                            <td>
                                                <a class="link-dark" href="{% url 'movies.show' id=item.movie.id %}">
                                                    {{ item.movie.name }}
                                                </a>
                                            </td>
                                            <td>${{ item.movie.price }}</td>
                                            <td>{{ item.quantity }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

moviesstore/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% block content %}
    <div class="p-3 mt-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card shadow p-3 mb-4 rounded">
                        <div class="card-body">
                            <h2>Reset Password</h2>
                            <form method="POST">
                                {% csrf_token %}
                                <p>
                                <label for="old_password">Old Password:</label>
                                <input type="password" name="old_password" id="old_password" class="form-control">
                                </p>
                                <p>
                                <label for="new_password">New Password:</label>
                                <input type="password" name="new_password" id="new_password" class="form-control">
                                </p>
                                <div class="text-center">
                                <button type="submit" class="btn bg-dark text-white">
                                    Submit
                                </button>
                                </div>
                            </form>
                            {% if messages %}
                                {% for message in messages %}
                                    <li class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                                        {{ message }}
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

moviesstore/accounts/templates/accounts/reset.html
{% extends 'base.html' %}
{% block content %}
    <div class="p-3 mt-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card shadow p-3 mb-4 rounded">
                        <div class="card-body">
                            Reset Password
                            </h2>
                            <hr />
                            {% if template_data.error %}
                                <div class="alert alert-danger" role="alert">
                                    {{ template_data.error }}
                                </div>
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                <p>
                                    <label for="username">Username</label>
                                    <input id="username" type="text" name="username" required autocomplete="username" class="form-control">
                                </p>
                                <p>
                                    <label for="new_password">New Password: </label>
                                    <input id="new_password" type="password" name="new_password" required class="form-control" minlength="8" maxlength="64">
                                </p>
                                <p>
                                    <label for="security_question">Security Question:</label>
                                    <select name="security_question" class="form-control" id="id_security_question">
                                        {% for choice in template_data.choices %}
                                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </p>
                                <p>
                                    <label for="security_answer">Security Question Answer</label>
                                    <input id="security_answer" type="text" name="security_answer" required class="form-control">
                                </p>
                                <div class="text-center">
                                    <button type="submit" class="btn bg-dark text-white">
                                        Reset Password
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

moviesstore/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3 mt-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow p-3 mb-4 rounded">
                    <div class="card-body">
                        <h2>Sign Up</h2>
                        <hr />
                        {% if template_data.error %}
                            <div class="alert alert-danger" role="alert">
                                {{ template_data.error }}
                            </div>
                        {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            <p>
                                <label for="username">Username</label>
                                <input id="username" type="text" name="username" required autocomplete="off" class="form-control" minlength="6" maxlength="32">
                            </p>
                            <p>
                                <label for="password1">Password</label>
                                <input id="password1" type="password" name="password1" required autocomplete="off" class="form-control" minlength="8" maxlength="32">
                            </p>
                            <p>
                                <label for="password2">Confirm Password</label>
                                <input id="password2" type="password" name="password2" required autocomplete="off" class="form-control" minlength="8" maxlength="32">
                            </p>
                                <label for="security_question">Security Question:</label>
                                <select name="security_question" class="form-control" id="id_security_question">
                                    {% for choice in template_data.choices %}
                                        <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                    {% endfor %}
                                </select>
                            <p>
                                <label for="security_answer">Security Question Answer</label>
                                <input id="security_answer" type="text" name="security_answer" required autocomplete="off" class="form-control" minlength="4" maxlength="32">
                            </p>
{#                            {{ template_data.form.as_p }}#}
{#                            {{ form.dropdown }}#}
                            <button type="submit" class="btn bg-dark text-white">
                                Sign Up
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}